### ISSUE TITLE
Problem when calculating mean for Pisaster counts

### ISSUE THREAD

**Issue by mjzahn** [mjzahn/fish549#2]
I am having trouble calculating the mean of Pisaster counts. When I try running mean() to the 'count' column, I am getting a warning message and NA is returned.

Please see Gist to find a reproducible example of the problem and the full warning message: [link here](https://gist.github.com/mjzahn/e84327ed4395e1e162d3e0f1db66e629)

If you know what's wrong, you can leave a response with a solution in this Github issue or on the Gist site. Any help is much appreciated!

**Comment by mdscheuerell** [comment]
Great job with your reprex, Marie!
