### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by mjzahn** [mjzahn/fish549#3]
Below is a screenshot showing that I have completed [Assignment 4](https://fish549.github.io/website/homework/week_04/hw_04_databases.html):

![Assignment4_postgres_screenshot](https://user-images.githubusercontent.com/58060156/216703078-d3a3810a-0fa5-475c-9ce7-b93313e779ce.JPG)

**Comment by mdscheuerell** [comment]
Well done, Marie!
